# Generated by Django 4.2 on 2024-02-29 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_num', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('space', models.CharField(max_length=30)),
                ('rooms_num', models.CharField(max_length=10)),
                ('rooms_service_num', models.CharField(max_length=10)),
                ('wc_num', models.CharField(max_length=10)),
                ('statues_apartment', models.CharField(max_length=50)),
                ('rent', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('maintenance', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='apartments_picture/')),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_num', models.CharField(max_length=50)),
                ('address_tower', models.CharField(max_length=255)),
                ('floors_num', models.CharField(max_length=10)),
                ('statues_tower', models.CharField(max_length=50)),
                ('value_tower', models.CharField(max_length=50)),
                ('picture_tower', models.ImageField(blank=True, null=True, upload_to='tower_picture/')),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('id_person', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='tenants_picture/')),
                ('notes', models.CharField(max_length=300)),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.apartments')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('id_person', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employees_picture/')),
                ('notes', models.CharField(max_length=300)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.tower')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.tower'),
        ),
    ]
